version: '3'
services:
  service_a:
    container_name: service_a
    build: ./service_a
    volumes:
      - ./service_a:/usr/src/app
    ports:
      - "5000:5000"
    restart: always
    depends_on:
      rabbitmq: 
        condition: service_healthy
      service_a_db:
        condition: service_healthy

  service_b:
    container_name: service_b
    build: ./service_b
    volumes:
      - ./service_b:/usr/src/app
    ports:
      - "5001:5001"
    restart: always
    depends_on:
      rabbitmq: 
        condition: service_healthy
      service_b_db:
        condition: service_healthy

  service_a_db:
    container_name: service_a_db
    image: mysql
    restart: always
    volumes:
      - ./data/a:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: a
      MYSQL_DATABASE: a
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root --password=$$MYSQL_ROOT_PASSWORD || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3

  service_b_db:
    container_name: service_b_db
    image: mysql
    restart: always
    volumes:
      - ./data/b:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: b
      MYSQL_DATABASE: b
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root --password=$$MYSQL_ROOT_PASSWORD || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 10s
      retries: 3
    
  # k6:
  #   container_name: k6
  #   image: grafana/k6
  #   volumes:
  #     - ./service_b/scripts:/scripts
  #   entrypoint: ["k6", "run", "/scripts/test.js"]