version: '3'
services:
  service_a:
    container_name: service_a
    build: ./service_a
    volumes:
      - ./service_a:/usr/src/app
    ports:
      - "5000:5000"
    restart: always
    depends_on:
      rabbitmq: 
        condition: service_healthy

  service_b:
    container_name: service_b
    build: ./service_b
    volumes:
      - ./service_b:/usr/src/app
    ports:
      - "5001:5001"
    restart: always
    depends_on:
      rabbitmq: 
        condition: service_healthy

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
      - "5552:5552"
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 10s
      retries: 3
    