apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment-a
  labels:
    app: webapp-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp-a
  template:
    metadata:
      labels:
        app: webapp-a
    spec:
      containers:
      - name: webapp-a
        image: service_a:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: mysql-secret-a
              key: mysql-password
        - name: DB_URL
          valueFrom:
            configMapKeyRef:
              name: mysql-config-a
              key: mysql-url
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service-a
spec:
  type: NodePort
  selector:
    app: webapp-a
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30001
