apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment-b
  labels:
    app: webapp-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp-b
  template:
    metadata:
      labels:
        app: webapp-b
    spec:
      containers:
      - name: webapp-b
        image: service_b:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5001
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: mysql-secret-b
              key: mysql-password
        - name: DB_URL
          valueFrom:
            configMapKeyRef:
              name: mysql-config-b
              key: mysql-url
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service-b
spec:
  type: NodePort
  selector:
    app: webapp-b
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
      nodePort: 30002
